### PR TITLE
dts update

### PR DESCRIPTION
**Pull request by Saikatsaha1996**

### CODE REVIEW

**Comment by lujianhua** [comment]
This device tree has been tested?

**Comment by Saikatsaha1996** [comment]
> This device tree has been tested?

@lujianhua No , from Postmarket os mainline told me use it single kernel.. and don't make another APKBUILD for your kernel..

**Comment by Saikatsaha1996** [comment]
> This device tree has been tested?

Okay don't update now .. i with give you update after test

**Comment by paulotassio1** [comment]
How to install?

**Pull request closed without merging**
